### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BenTheElder**
https://github.com/kubernetes-sigs/llm-instance-gateway/issues/41

### CODE REVIEW

**Comment by BenTheElder** [comment]
I think this is reasonable? It allows WG-Serving to claim credit for launching this project, drives interest in the WG, but still clearly identifies the sponsoring SIG and the official subproject listing. I think the split into two sentences is more readable.

**Comment by kfswain** [comment]
> I think this is reasonable? It allows WG-Serving to claim credit for launching this project, drives interest in the WG, but still clearly identifies the sponsoring SIG and the official subproject listing. I think the split into two sentences is more readable.

Yeah, I am definitely fine with this.

**Comment by terrytangyuan** [comment]
Thanks!

**Pull request merged**
