### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by smarterclayton**
Abdullah and I will act as approvers on Google side for code changes.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Comment by Jeffwan** [comment]
@kfswain Could you apply the `kubernetes-sig` member first? We can add you into the OWNERS after that.

**Review by Jeffwan — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
> kfswain
> User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

I can sponsor membership. Need some non-googler "reviewer or approver in at least one OWNERS" to +1 as well. I think this repository counts if any of other wg serving chairs can sponsor?

**Comment by terrytangyuan** [comment]
Yep on it https://github.com/kubernetes/org/issues/5146

**Comment by kfswain** [comment]
Ahh changes haven't percolated yet. Should be fine in the AM

**Comment by Jeffwan** [comment]
it takes some time to be added to the organization. Let's verify the owner file later

**Pull request merged**
